### ISSUE TITLE
`into_io` does not work for `std::fs::File`

### ISSUE THREAD

**Issue by quininer** [Rufflewind/tokio-file-unix#2]
https://github.com/quininer/tokio-file-unix/blob/test/examples/test_file.rs

```rust
    let file = fs::File::create("aaa.txt").unwrap();
    let file = File::new_nb(file).unwrap().into_io(&handle).unwrap();
```

will panic:
```
$ cargo run --example test_file
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/test_file`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 1, message: "Operation not permitted" } }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by quininer** [comment]
http://man7.org/linux/man-pages/man2/epoll_ctl.2.html

```
 EPERM  The target file fd does not support epoll.  This error can
              occur if fd refers to, for example, a regular file or a
              directory.
```

I think this is because the regular file does not support epoll.

**Comment by Rufflewind** [comment]
Yeah IIRC when I tried this on `/dev/null` it failed with the same error code.  Unless there's a way to choose a different backend with mio, the best we can do probably is to document this limitation.

**Comment by quininer** [comment]
I think should rename the crate to `tokio-stdio-unix`.

**Comment by Rufflewind** [comment]
It works for pipes / FIFOs and sockets though, all of which are considered “files” on Unix.

**Comment by Rufflewind** [comment]
This also affects standard I/O if they are redirected to regular files:

```sh
cargo run --example stdin <regularfile # error!
cat regularfile | cargo run --example stdin # ok
```

**Comment by Rufflewind** [comment]
See if this fixes the problem? https://github.com/Rufflewind/tokio-file-unix/commit/fa5f293a92c1109dc7c84501d8ea4d246baa5aff

**Comment by quininer** [comment]
Very nice, but i will wait for tokio AIO support.
