### ISSUE TITLE
Add clarifying documentation around "file-like" objects

### ISSUE THREAD

**Issue by twmb** [Rufflewind/tokio-file-unix#4]
Hi! This crate is great, but I think the documentation needs to be more explicit in some areas. Specifically, if I didn't know better, I would expect to be able to use this crate on regular (disk backed) files. Unfortunately, non-blocking mode for regular files does (next to) nothing in that [reads and writes never block](https://www.remlab.net/op/nonblock.shtml), but they do put the thread do sleep.

I think documentation should be added clarifying that users should not use this crate for regular files - if they do, reads / writes will put their threads to sleep for longer than they may expect, which is likely the opposite behavior people are going for when using futures.

**Comment by Rufflewind** [comment]
Thanks!  I have noted this in the docs.
