### ISSUE TITLE
Documentation link from Github

### ISSUE THREAD

**Issue by vi** [Rufflewind/tokio-file-unix#5]
README.md should also have a link to https://docs.rs/tokio-file-unix, like in most Rust projects.

**Comment by Rufflewind** [comment]
You can click on the `docs` badge to read the documentation:

[![Documentation](https://docs.rs/tokio-file-unix/badge.svg)](https://docs.rs/tokio-file-unix)

Does that suffice?

**Comment by vi** [comment]
Yes. I've just got used to look at the literal word "Documentation" below the badges.

Badges look like images and images get filtered away when I look for text.
